#!/usr/bin/env bash

# Script to set up .env file for OpenCL-enabled GPUs (AMD, NVIDIA, Intel)

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
ROOT="$DIR"/../
cd "$ROOT"

echo "Setting up .env file for OpenCL-enabled GPU..."

# Create .env file if it doesn't exist
if [ ! -f "$ROOT"/.env ]; then
  echo "# Environment variables for openpilot" > "$ROOT"/.env
  echo "# Generated by setup_device_env.sh for OpenCL-enabled GPUs (AMD, NVIDIA, Intel)" >> "$ROOT"/.env
fi

# Set Python path
echo "Setting PYTHONPATH..."
if grep -q "PYTHONPATH=" "$ROOT"/.env; then
  sed -i 's/.*PYTHONPATH=.*/PYTHONPATH='"$PWD"'/' "$ROOT"/.env
else
  echo "PYTHONPATH=${PWD}" >> "$ROOT"/.env
fi

# Set DEV to CL for GPU support
echo "Setting DEV=CL for GPU support..."
if grep -q "export DEV=" "$ROOT"/.env; then
  sed -i 's/.*export DEV=.*/export DEV=CL  # Use OPENCL GPU for model inference/' "$ROOT"/.env
else
  echo "export DEV=CL  # Use OPENCL GPU for model inference" >> "$ROOT"/.env
fi

# Ensure AMD and USBGPU variables are not set (to use CL backend)
echo "Ensuring AMD and USBGPU variables are not set..."
if grep -q "export AMD=" "$ROOT"/.env; then
  sed -i '/export AMD=/d' "$ROOT"/.env
fi

if grep -q "export USBGPU=" "$ROOT"/.env; then
  sed -i '/export USBGPU=/d' "$ROOT"/.env
fi

# Enable ZMQ for IPC
echo "Enabling ZMQ for IPC..."
if grep -q "export ZMQ=" "$ROOT"/.env; then
  sed -i 's/.*export ZMQ=.*/export ZMQ=1/' "$ROOT"/.env
else
  echo "export ZMQ=1  # Enable ZMQ for IPC" >> "$ROOT"/.env
fi

# Enable webcam support
echo "Enabling webcam support..."
if grep -q "export USE_WEBCAM=" "$ROOT"/.env; then
  sed -i 's/.*export USE_WEBCAM=.*/export USE_WEBCAM=1/' "$ROOT"/.env
else
  echo "export USE_WEBCAM=1  # Enable webcam support" >> "$ROOT"/.env
fi

# Set road camera to default (0) and disable other cameras
echo "Setting road camera to default (0)..."
if grep -q "export ROAD_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export ROAD_CAM=.*/export ROAD_CAM=0  # Default road camera setting (dev/video0)/' "$ROOT"/.env
else
  echo "export ROAD_CAM=0  # Default road camera setting (dev/video0)" >> "$ROOT"/.env
fi

# Disable driver camera (set to empty to prevent access to /dev/video2)
echo "Disabling driver camera..."
if grep -q "export DRIVER_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export DRIVER_CAM=.*/export DRIVER_CAM=""  # Disable driver camera/' "$ROOT"/.env
else
  echo 'export DRIVER_CAM=""  # Disable driver camera' >> "$ROOT"/.env
fi

# Disable wide camera (set to empty to prevent access to wide camera device)
echo "Disabling wide camera..."
if grep -q "export WIDE_CAM=" "$ROOT"/.env; then
  sed -i 's/.*export WIDE_CAM=.*/export WIDE_CAM=""  # Disable wide camera/' "$ROOT"/.env
else
  echo 'export WIDE_CAM=""  # Disable wide camera' >> "$ROOT"/.env
fi

# Set parameter directory to project root for PC environment
echo "Setting parameter directory to project root..."
if grep -q "export PARAMS_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export PARAMS_ROOT=.*|export PARAMS_ROOT='"$PWD"'/data/params  # Parameter directory for PC environment|' "$ROOT"/.env
else
  echo "export PARAMS_ROOT=${PWD}/data/params  # Parameter directory for PC environment" >> "$ROOT"/.env
fi

# Set log and video storage directories to project root
echo "Setting log and video storage directories..."
if grep -q "export LOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export LOG_ROOT=.*|export LOG_ROOT='"$PWD"'/data/realdata  # Log and video storage directory|' "$ROOT"/.env
else
  echo "export LOG_ROOT=${PWD}/data/realdata  # Log and video storage directory" >> "$ROOT"/.env
fi

if grep -q "export SWAGLOG_ROOT=" "$ROOT"/.env; then
  sed -i 's|.*export SWAGLOG_ROOT=.*|export SWAGLOG_ROOT='"$PWD"'/data/log  # System log storage directory|' "$ROOT"/.env
else
  echo "export SWAGLOG_ROOT=${PWD}/data/log  # System log storage directory" >> "$ROOT"/.env
fi

# Enable human-readable log format
echo "Enabling human-readable log format..."
if grep -q "export LOG_READABLE=" "$ROOT"/.env; then
  sed -i 's/.*export LOG_READABLE=.*/export LOG_READABLE=1  # Enable human-readable log format/' "$ROOT"/.env
else
  echo "export LOG_READABLE=1  # Enable human-readable log format" >> "$ROOT"/.env
fi

# Enable FPS display for debugging
echo "Enabling FPS display..."
if grep -q "export DEBUG_FPS=" "$ROOT"/.env; then
  sed -i 's/.*export DEBUG_FPS=.*/export DEBUG_FPS=1  # Enable FPS display for debugging/' "$ROOT"/.env
else
  echo "export DEBUG_FPS=1  # Enable FPS display for debugging" >> "$ROOT"/.env
fi

# Set IMAGE=0 for CL device
echo "Setting IMAGE=0 for CL device..."
if grep -q "export IMAGE=" "$ROOT"/.env; then
  sed -i 's/.*export IMAGE=.*/export IMAGE=0  # Required for CL device (OpenCL) image handling/' "$ROOT"/.env
else
  echo "export IMAGE=0  # Required for CL device (OpenCL) image handling" >> "$ROOT"/.env
fi

# Add TARGET_ARCH environment variable support for manual GPU architecture specification
echo "Adding TARGET_ARCH support for manual GPU architecture specification..."

# Set TARGET_ARCH with repeatable execution support
echo "Setting TARGET_ARCH..."
if grep -q "export TARGET_ARCH=" "$ROOT"/.env; then
  sed -i 's/.*export TARGET_ARCH=.*/# export TARGET_ARCH=  # Manually specify GPU architecture (e.g., gfx1010 for AMD, compute_61 for NVIDIA)/' "$ROOT"/.env
else
  echo "" >> "$ROOT"/.env
  echo "# TARGET_ARCH - Manually specify GPU architecture (e.g., 'gfx1010' for AMD, 'compute_61' for NVIDIA)" >> "$ROOT"/.env
  echo "# Uncomment the line below and set the appropriate architecture for your GPU" >> "$ROOT"/.env
  echo "# export TARGET_ARCH=" >> "$ROOT"/.env
fi

# Add OpenCL specific environment variables for fine-grained control
echo "Adding OpenCL specific environment variables..."

# Set CL_ARCH_DETECTION with repeatable execution support
echo "Setting CL_ARCH_DETECTION..."
if grep -q "export CL_ARCH_DETECTION=" "$ROOT"/.env; then
  sed -i 's/.*export CL_ARCH_DETECTION=.*/# export CL_ARCH_DETECTION=1  # Enable AMD GPU architecture auto-detection (only works when explicitly set to 1)/' "$ROOT"/.env
else
  echo "# CL_ARCH_DETECTION - Enable AMD GPU architecture auto-detection (only works when explicitly set to 1)" >> "$ROOT"/.env
  echo "# export CL_ARCH_DETECTION=1" >> "$ROOT"/.env
fi

# Set CL_OPTIMIZATION_LEVEL with repeatable execution support
echo "Setting CL_OPTIMIZATION_LEVEL..."
if grep -q "export CL_OPTIMIZATION_LEVEL=" "$ROOT"/.env; then
  sed -i 's/.*export CL_OPTIMIZATION_LEVEL=.*/# export CL_OPTIMIZATION_LEVEL=1  # Standard optimization for general use (0=none, 2=aggressive, default=use OpenCL defaults)/' "$ROOT"/.env
else
  echo "" >> "$ROOT"/.env
  echo "# CL_OPTIMIZATION_LEVEL - Control OpenCL compilation optimization level (0=none, 2=aggressive, default=use OpenCL defaults)" >> "$ROOT"/.env
  echo "# export CL_OPTIMIZATION_LEVEL=1  # Standard optimization for general use" >> "$ROOT"/.env
fi

echo ""
echo ".env file setup complete for OpenCL-enabled GPU!"
echo "Contents of .env file:"
echo "======================================"
cat "$ROOT"/.env
echo "======================================"
echo ""
echo "To apply these settings, run: source .env"
echo ""
echo "Note: If you experience issues with GPU architecture detection, you can manually specify it by editing the .env file and uncommenting the TARGET_ARCH line."
echo "Example: For NVIDIA GT640M, you might use export TARGET_ARCH=compute_30"
echo ""
echo "Additional OpenCL controls available:"
echo "- CL_ARCH_DETECTION: Enable AMD architecture auto-detection (only works when explicitly set to 1)"
echo "- CL_OPTIMIZATION_LEVEL: Adjust compilation optimization (0=none, 2=aggressive, default=use OpenCL defaults)"
